joint_ids_map: [3, 0, 9, 6, 4, 1, 10, 7, 5, 2, 11, 8]
step_dt: 0.02
stiffness: [25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0, 25.0]
damping: [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]
default_joint_pos: [0.1, -0.1, 0.1, -0.1, 0.8, 0.8, 1.0, 1.0, -1.5, -1.5, -1.5, -1.5]
commands:
  base_velocity:
    ranges:
      lin_vel_x: [-1.0, 1.0]
      lin_vel_y: [-0.4, 0.4]
      ang_vel_z: [-1.0, 1.0]
      heading: null
actions:
  JointPositionAction:
    clip:
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    - [-100.0, 100.0]
    joint_names: [.*]
    scale: [0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25]
    offset: [0.1, -0.1, 0.1, -0.1, 0.8, 0.8, 1.0, 1.0, -1.5, -1.5, -1.5, -1.5]
    joint_ids: null
observations:
  base_ang_vel:
    params: {}
    clip: [-100, 100]
    scale: [0.2, 0.2, 0.2]
    history_length: 5
  projected_gravity:
    params: {}
    clip: [-100, 100]
    scale: [1.0, 1.0, 1.0]
    history_length: 5
  velocity_commands:
    params: {command_name: base_velocity}
    clip: [-100, 100]
    scale: [1.0, 1.0, 1.0]
    history_length: 5
  joint_pos_rel:
    params: {}
    clip: [-100, 100]
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 5
  joint_vel_rel:
    params: {}
    clip: [-100, 100]
    scale: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]
    history_length: 5
  last_action:
    params: {}
    clip: [-100, 100]
    scale: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
    history_length: 5
