FSM:
  Passive:
    mode: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    kd: [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]
  FixStand:
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
    ts: [0, 1, 2]
    qs: [
      [],
      [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65],
      # [0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5, 0., 0.8, -1.5],
      [-0.1, 0.8, -1.5, 0.1, 0.8, -1.5, -0.1, 1.0, -1.5, 0.1, 1.0, -1.5],
    ]
  Velocity:
    policy_dir: unitree_rl_lab
    policy_name: policy.onnx
    joystick_rate: 0.5
    
